name: Davey Marvich
favicon: null
layout_spectrum: 0.28366
typography_spectrum: 0.8568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff00ff'
    - '#01ffff'
    - '#0000fe'
    - '#fe9a00'
  brandStrength: 0.5197133
  lightness: 0.3085102
  saturation: 0.6813598
  rhythmicContrast: 0.06127067
purpose: []
