name: Davey Marvich
favicon: null
layout_spectrum: 0.5234
typography_spectrum: 0.81733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0098d7'
    - '#002221'
    - '#a76477'
    - '#d9bda4'
    - '#742e3b'
  brandStrength: 0.5197133
  lightness: 0.3085102
  saturation: 0.6813598
  rhythmicContrast: 0.06127067
purpose: []
